api_platform:
  title: "Interviews Management"
  description: "A Symfony REST API to manage job-interviews."
  version: "1.0.0"
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
