# app:
#   path: /{params}
#   controller: App\Controller\DefaultController::index
#   requirements:
#     params: "^(?!admin|api).+"

# path to token
authentication_token:
  path: /api/login
  methods: ["POST"]
